services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Pforum\:
    resource: '../Classes/*'

  JWeiland\Pforum\Command\InformAttendeesAboutNewTopic:
    tags:
      - name: 'console.command'
        command: 'pforum:informattendeesaboutnewtopic'

  JWeiland\Pforum\Command\InformAttendeesAboutNewPosts:
    tags:
      - name: 'console.command'
        command: 'pforum:informattendeesaboutnewpost'

  JWeiland\Pforum\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PostProcessFluidVariablesEvent

  JWeiland\Pforum\EventListener\ApplyEmailAsMandatoryIfNeededEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PreProcessControllerActionEvent
  JWeiland\Pforum\EventListener\AssignMediaTypeConverterForTopicEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PreProcessControllerActionEvent
  JWeiland\Pforum\EventListener\AssignMediaTypeConverterForPostEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PreProcessControllerActionEvent
  JWeiland\Pforum\EventListener\ApplyUsernameAsMandatoryIfNeededEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PreProcessControllerActionEvent
